name: GitHub Pages Deploy
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install & Build React App
        run: npm install && npm run build
        
      - name: Deployment in Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build

      
